ClassWork/week_4/timetracking/config/routes.rb
Rails.application.routes.draw do

   get "/" => "site#home"

   resources :projects, only: [:destory, :index, :show, :new, :create] do
      resources :entries, only: [:destory, :index, :new, :create, :edit, :update]
    end

end

ClassWork/week_4/timetracking/app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :project
	validates :hours, numericality: {only_integer: true}, presence: true
	validates :mintues, numericality: {only_integer: true} presence: true
	validates :date, presence: true
	
	validates_associated :project
end

ClassWork/week_4/timetracking/app/models/particpation.rb
class Particpation < ActiveRecord::Base
  belongs_to :person
  belongs_to :project
end

ClassWork/week_4/timetracking/app/models/person.rb
class Person < ActiveRecord::Base
	has_many: participations
	has_many: projects, through: :participations
end

ClassWork/week_4/timetracking/app/models/project.rb
class Project < ActiveRecord::Base

	has_many :entries, dependent: :destory
	has_many :participation
	has_many :people, through: :participation

	validates :name, presence: true, uniqueness: true, length: {maximum: 30}, format:{with: /(\w\s)+/}

	def self.clean_odd	
		where("created_at <= ?", d-1.week.ago).destory_all
	end

	def self.last_created_projects(arg)
		@projects = Project.limit(10)
	
	end

	def total_hours_in_month(month, year)
		sum = 0
		minutes = 0

		month = Date.new(year, month)


		entires.where(date: month.beginning_of_month..month.end_of_month).each do |entry|
			sum += entry.hours
			mintues += entry.minutes
		end
		hours_mintues = mintues / 60

		sum + hours_mintues
	end

end

ClassWork/week_4/timetracking/app/controllers/entries_controller.rb
 class EntriesController < ApplicationController
  def edit
  	@project = Project.find(params[:project_id])
  	@entry = @project.entries.where(id: params[:id]).first
  end


  def index
  	@project = Project.find_by(id: params[:id])
  	unless @project
  		render "no_project"
  	end 
  end

  def new
  	@project = Project.find(params[:project_id])
  	@entry = @project.entries.new(entry_params)

  end

  
  def create
  	@project = Project.find params[:project_id]
  	@entry = @project.entries.new params[:entry]

  	if @entry.save
  			redirect_to action: 'index', controller:
  			'entries', project_id: @project_id

  	else
  			render 'new'

  	end
  end

  def update
  	@project = Project.find params[:project_id]
  	@entry = @project.entries.new params[:entry]

  	if @entry.update_attributes(entry_params)
  			redirect_to project_entries_path(@project)

  	else
  			render 'edit'

  	end
  end

  private

  	def entry_params
  			params.require(:entry).permit(:hours, :mintues, :date)
  	end

end

ClassWork/week_4/timetracking/app/controllers/index_controller.rb
class IndexController < ApplicationController
end

ClassWork/week_4/timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	def index
		@projects = Project.last_created_projects(10)
		if @projects.empty?

			render "no_project" 
		else 
			render "index"
		end

	end

	def show
		@project= Project.find(id: params[:id])

	end


end

ClassWork/week_4/timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		render "home"
	end

	def contact
		

	end

end

ClassWork/week_4/timetracking/app/helpers/application_helper.rb
module ApplicationHelper
def flash_message
	if flash[:notice]
end 
end

ClassWork/week_4/timetracking/app/helpers/enteries_helper.rb
module EnteriesHelper
end

ClassWork/week_4/timetracking/app/helpers/index_helper.rb
module IndexHelper
end

ClassWork/week_4/timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

ClassWork/week_4/timetracking/app/helpers/site_helper.rb
module SiteHelper
end

ClassWork/week_4/timetracking/app/views/enteries/_form.html.erb
<%= form_for [@project, @entry] do |f| %>
<% f.label :hours %>
<% f.text_input :hours %>
<br>
<% f.label :mintues %>
<% f.text_input :mintues %>
<br>
<% f.label :date %>
<% f.text_input :date %>
<br>

<% f.submit "Save" %>
<%= link_to "Cancel", project_entries_path(@project)%>
<% end %>

ClassWork/week_4/timetracking/app/views/enteries/edit.html.erb
<% flash_message %>
<%= render'form' %>

ClassWork/week_4/timetracking/app/views/enteries/index.html.erb
<% if flash[:notice] %>
	<%= flash[:notice] %>
<% end %>


<h1><%= @project.name %></h1>


<ul>
<% @project.entries.each  do |entry| %>

	<li><%= "#{entry.hours} #{entry.minutes}" %></li>
	<%=link_to("Edit Link"), edit_project_entry_path(@project, entry)) %>
	<% link_to("Delete", edit_project_entry_path(@project,entry),  method: :delete date: {confirm: "Are you sure you want to delete this entry?"}) %>
<% end %>
</ul>
<%= link_to("Go To Projects", projects_path) %>
<%= link_to("New Entry",new_project_entry_path(@project) %>

ClassWork/week_4/timetracking/app/views/enteries/new.html.erb
<% if @entry.errors.any? %>

<ul>
	<% @entry.erros.full_messages.each do | error_msg| %>
		<li><%= error_msg %></li>
		<%end%>
</ul>
<%end%>

<%= form_for [@project, @entry] do |f| %>
<%= f.label :hours %>
<%= f.text_feild :hours %>
<br>
<%= f.label :minutes %>
<%= f.text_feild :mintues %>
<br>
<%= f.label :date %>
<%= f.text_feild :date %>
<br>

<%= f.submit 'Save' %>

<%end%>

<%= link_to("Cancel", project_entries_path(@project)) %>

ClassWork/week_4/timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ClassWork/week_4/timetracking/app/views/projects/index.html.erb
<ul>
<h1>Projects</h1>
<% @projects.each do |p| %>
	<li>
		<!-- <p><%=p.id %></p> -->
		<p><%=p.name %></p>
		<p><%=p.description %></p>
		
	<li>

<% end %>
</ul>

ClassWork/week_4/timetracking/app/views/projects/show.html.erb
<h1><%=@project.name %></h1>
<p><%= @project.description %></p>

ClassWork/week_4/timetracking/app/views/site/contact.html.erb
<p> contact@example.com </p>

ClassWork/week_4/timetracking/app/views/site/home.html.erb
<h1> Welcome to this timetracking tool </h1>

<p>Ironhack powered</p>